### ISSUE TITLE
Does it works with 'ng-controller='Contoller as XXX' pattern?

### ISSUE THREAD

**Issue by Starojitski** [wix/angular-tree-control#91]
i am not sure whether this is the right place to ask this kind of questions but i need some help.

i followed your instructions
- added files
- added dependency to the module ```angular.module('minerva', ['mgcrea.ngStrap', 'treeControl']);```
- added controller:

    angular.module('minerva')
        .controller('MenuController', function () {
            this.os_tree = {
                treeOptions: { ... },
                dataForTheTree:[ ... ]
            };
        });

- added 'treecontrol' to template.

	<div ng-controller='MenuController as menu'>
		<treecontrol class='tree-classic'
					 tree-model='menu.os_tree.dataForTheTree'
					 options='menu.os_tree.treeOptions'
					 selected-node='node1'>
			employee: {{node.name}} age {{node.age}}
		</treecontrol>
	</div>
    
And after all this work all i get is 

 TypeError: undefined is not a function
    at http://vogdots/plugins/angular/angular-tree-control.js:218:39
    at http://vogdots/plugins/angular/1.3.9/angular.min.js:70:370
    at $ (http://vogdots/plugins/angular/1.3.9/angular.min.js:70:426)
    at v (http://vogdots/plugins/angular/1.3.9/angular.min.js:59:401)
    at g (http://vogdots/plugins/angular/1.3.9/angular.min.js:52:9)
    at v (http://vogdots/plugins/angular/1.3.9/angular.min.js:59:345)
    at g (http://vogdots/plugins/angular/1.3.9/angular.min.js:52:9)
    at v (http://vogdots/plugins/angular/1.3.9/angular.min.js:59:345)
    at g (http://vogdots/plugins/angular/1.3.9/angular.min.js:52:9)
    at g (http://vogdots/plugins/angular/1.3.9/angular.min.js:52:26) <treecontrol class="tree-classic ng-isolate-scope" tree-model="os_tree.dataForTheTree" options="os_tree.treeOptions" selected-node="node1">

Could it be that i am not using $scope? Or is there something else i am doing wrong?

**Comment by wolution** [comment]
I have the same problem, can anybody help with this?
